INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (7, 7, 1913, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1913;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (84, 7, 652, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 652;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (29, 7, 473, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 473;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (103, 7, 620, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 620;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (8, 8, 790, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 790;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (111, 8, 1408, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1408;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (101, 8, 1, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (102, 8, 566, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 566;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (113, 9, 1379, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1379;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (87, 9, 1742, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1742;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (32, 9, 125, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 125;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (77, 9, 1886, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1886;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (14, 10, 947, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 947;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (86, 10, 687, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 687;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (46, 10, 2128, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2128;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (74, 10, 2238, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2238;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (6, 11, 2149, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2149;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (66, 11, 419, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 419;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (104, 11, 1637, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1637;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (97, 11, 1039, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1039;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (77, 12, 1887, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1887;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (29, 12, 498, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 498;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (69, 12, 162, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 162;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (11, 12, 1170, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1170;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (22, 13, 1108, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1108;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (111, 13, 1415, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1415;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (63, 13, 1993, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1993;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 13, 1845, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1845;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 14, 1823, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1823;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (23, 14, 1206, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1206;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (92, 14, 910, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 910;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (116, 14, 50, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 50;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (26, 15, 116, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 116;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (85, 15, 349, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 349;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (41, 15, 751, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 751;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (34, 15, 733, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 733;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (50, 16, 433, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 433;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (57, 16, 431, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 431;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (16, 16, 1682, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1682;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (49, 16, 2344, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2344;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (56, 17, 1275, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1275;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (93, 17, 87, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 87;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (66, 17, 420, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 420;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (42, 17, 2400, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2400;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (118, 18, 1319, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1319;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (85, 18, 334, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 334;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (52, 18, 838, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 838;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (67, 18, 382, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 382;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (89, 19, 1297, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1297;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (66, 19, 389, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 389;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (10, 19, 1466, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1466;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (109, 19, 1351, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1351;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (30, 20, 284, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 284;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (65, 20, 1653, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1653;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (14, 20, 948, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 948;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (72, 20, 1055, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1055;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (41, 21, 763, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 763;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (42, 21, 2409, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2409;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (45, 21, 2014, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2014;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 21, 1846, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1846;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 22, 1827, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1827;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (57, 22, 425, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 425;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (7, 22, 1915, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1915;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (44, 23, 2073, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2073;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (95, 23, 1493, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1493;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (53, 23, 1793, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1793;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (97, 23, 1018, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1018;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (77, 24, 1874, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1874;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (9, 24, 534, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 534;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (99, 24, 2340, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2340;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (81, 25, 261, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 261;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (74, 25, 2210, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2210;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (11, 25, 1171, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1171;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (59, 26, 2184, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2184;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (97, 26, 1040, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1040;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (50, 26, 446, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 446;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (106, 26, 1590, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1590;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (72, 27, 1056, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1056;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (60, 27, 2371, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2371;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (87, 27, 1763, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1763;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (8, 27, 779, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 779;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (108, 28, 1454, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1454;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (103, 28, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (50, 28, 434, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 434;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (60, 28, 2364, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2364;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (101, 28, 29, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 29;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (23, 29, 1207, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1207;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (10, 29, 1467, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1467;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (108, 29, 1423, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1423;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (16, 30, 1695, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1695;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (24, 30, 2452, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2452;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (92, 30, 903, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 903;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (30, 30, 308, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 308;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (108, 31, 1416, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1416;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 31, 1828, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1828;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (104, 31, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (2, 31, 176, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 176;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (97, 32, 1033, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1033;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (53, 32, 1806, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1806;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (50, 32, 435, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 435;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (86, 33, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (78, 33, 219, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 219;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (38, 33, 969, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 969;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (111, 33, 1393, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1393;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (103, 33, 605, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 605;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (105, 34, 1194, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1194;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (46, 34, 2115, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2115;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (52, 34, 852, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 852;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (7, 34, 1891, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1891;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (111, 35, 1400, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1400;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (36, 35, 1963, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1963;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (78, 35, 223, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 223;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (29, 35, 499, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 499;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (113, 36, 1387, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1387;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (69, 36, 152, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 152;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (52, 36, 843, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 843;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (93, 36, 88, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 88;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (34, 37, 707, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 707;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (108, 37, 1455, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1455;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (27, 37, 2327, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2327;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (75, 37, 323, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 323;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (89, 38, 1289, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1289;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (56, 38, 1283, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1283;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (17, 38, 1549, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1549;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (50, 38, 450, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 450;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (92, 39, 911, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 911;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (22, 39, 1088, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1088;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (95, 39, 1508, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1508;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (73, 39, 1009, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1009;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (118, 40, 1320, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1320;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (16, 40, 1696, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1696;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (73, 41, 1000, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1000;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (13, 41, 944, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 944;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (39, 41, 2485, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2485;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (43, 41, 2088, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2088;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (105, 42, 1198, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1198;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (63, 42, 1978, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1978;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (87, 42, 1764, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1764;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (60, 43, 2365, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2365;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (29, 43, 474, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 474;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (56, 43, 1234, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1234;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (101, 43, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (38, 43, 977, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 977;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (27, 44, 2301, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2301;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (109, 44, 1352, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1352;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (33, 44, 996, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 996;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (22, 44, 1089, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1089;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (24, 45, 2453, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2453;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (66, 45, 394, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 394;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (89, 45, 1286, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1286;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (98, 45, 1930, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1930;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (108, 46, 1417, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1417;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (95, 46, 1484, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1484;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (23, 46, 1226, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1226;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (72, 46, 1046, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1046;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (33, 47, 992, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 992;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (53, 47, 1807, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1807;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (84, 48, 647, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 647;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (43, 48, 2091, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2091;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (39, 48, 2479, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2479;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (87, 48, 1765, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1765;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (74, 49, 2246, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2246;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (13, 49, 939, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 939;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (115, 49, 636, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 636;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (60, 49, 2362, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2362;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (112, 50, 1713, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1713;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (27, 50, 2326, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2326;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (99, 50, 2342, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2342;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (109, 50, 1364, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1364;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (89, 51, 1284, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1284;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (71, 51, 2438, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2438;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (109, 51, 1340, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1340;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (63, 51, 2005, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2005;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (38, 52, 978, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 978;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 52, 1847, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1847;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (101, 52, "on hold", 2);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (109, 52, 1339, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1339;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (16, 52, 1683, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1683;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (118, 53, 1332, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1332;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (32, 53, 134, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 134;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (4, 53, 2456, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2456;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (111, 53, 1394, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1394;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (97, 54, 1011, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1011;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (119, 54, 1698, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1698;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (82, 54, 662, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 662;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (66, 54, 390, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 390;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (2, 55, 182, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 182;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (103, 55, 597, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 597;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (103, 56, 587, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 587;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (113, 56, 1388, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1388;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (51, 57, 814, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 814;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (39, 57, 2480, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2480;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (71, 58, 2439, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2439;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (69, 58, 168, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 168;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (38, 59, 958, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 958;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (22, 59, 1090, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1090;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (70, 60, 358, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 358;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (27, 60, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (31, 60, 1888, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1888;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (34, 61, 742, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 742;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (118, 61, 1306, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1306;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (59, 62, 2201, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2201;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (51, 62, 805, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 805;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (7, 63, 1906, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1906;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (111, 63, 1395, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1395;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (46, 64, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (92, 64, 912, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 912;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (86, 64, 688, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 688;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (74, 65, 2211, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2211;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (2, 65, 183, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 183;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (71, 66, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (93, 66, 89, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 89;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (87, 66, 1767, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1767;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (12, 67, 918, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 918;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (7, 67, 1914, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1914;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (116, 68, 30, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 30;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (17, 68, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (27, 68, 2310, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2310;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (91, 69, 861, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 861;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (80, 69, 2286, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2286;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (71, 70, 2440, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2440;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (94, 70, 92, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 92;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (85, 71, 335, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 335;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (98, 71, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (63, 71, 1992, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1992;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (26, 72, 117, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 117;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (92, 72, 879, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 879;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (73, 73, 1010, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1010;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (9, 73, 535, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 535;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (28, 74, 519, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 519;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (56, 74, 1276, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1276;
UPDATE book_rental SET rental_status = "rented" WHERE id = 1;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 2;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 2;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 652;
UPDATE book_rental SET rental_status = "returned" WHERE id = 3;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 473;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 4;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 4;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 620;
UPDATE book_rental SET rental_status = "rented" WHERE id = 5;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 6;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 7;
UPDATE book_rental SET rental_status = "returned" WHERE id = 8;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 566;
UPDATE book_rental SET rental_status = "rented" WHERE id = 9;
UPDATE book_rental SET rental_status = "rented" WHERE id = 10;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 11;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 12;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 12;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1886;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 13;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 13;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 947;
UPDATE book_rental SET rental_status = "returned" WHERE id = 14;
UPDATE book_rental SET rental_status = "returned" WHERE id = 14;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 15;
UPDATE book_rental SET rental_status = "rented" WHERE id = 16;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 17;
UPDATE book_rental SET rental_status = "rented" WHERE id = 18;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 19;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 19;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1637;
UPDATE book_rental SET rental_status = "rented" WHERE id = 20;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 21;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 21;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1887;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 22;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 22;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 498;
UPDATE book_rental SET rental_status = "rented" WHERE id = 23;
UPDATE book_rental SET rental_status = "rented" WHERE id = 24;
UPDATE book_rental SET rental_status = "rented" WHERE id = 25;
UPDATE book_rental SET rental_status = "rented" WHERE id = 26;
UPDATE book_rental SET rental_status = "rented" WHERE id = 27;
UPDATE book_rental SET rental_status = "rented" WHERE id = 28;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 29;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 29;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1823;
UPDATE book_rental SET rental_status = "returned" WHERE id = 30;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1206;
UPDATE book_rental SET rental_status = "returned" WHERE id = 31;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 910;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 32;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 32;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 50;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 33;
UPDATE book_rental SET rental_status = "rented" WHERE id = 34;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 35;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 35;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 751;
UPDATE book_rental SET rental_status = "rented" WHERE id = 36;
UPDATE book_rental SET rental_status = "returned" WHERE id = 37;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 433;
UPDATE book_rental SET rental_status = "rented" WHERE id = 38;
UPDATE book_rental SET rental_status = "rented" WHERE id = 39;
UPDATE book_rental SET rental_status = "rented" WHERE id = 40;
UPDATE book_rental SET rental_status = "rented" WHERE id = 41;
UPDATE book_rental SET rental_status = "returned" WHERE id = 42;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 87;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 43;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 43;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 420;
UPDATE book_rental SET rental_status = "rented" WHERE id = 44;
UPDATE book_rental SET rental_status = "rented" WHERE id = 45;
UPDATE book_rental SET rental_status = "rented" WHERE id = 46;
UPDATE book_rental SET rental_status = "rented" WHERE id = 47;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 48;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 49;
UPDATE book_rental SET rental_status = "returned" WHERE id = 50;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 389;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 51;
UPDATE book_rental SET rental_status = "rented" WHERE id = 52;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 53;
UPDATE book_rental SET rental_status = "rented" WHERE id = 54;
UPDATE book_rental SET rental_status = "returned" WHERE id = 55;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 948;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 56;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 56;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1055;
UPDATE book_rental SET rental_status = "rented" WHERE id = 57;
UPDATE book_rental SET rental_status = "returned" WHERE id = 58;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 2409;
UPDATE book_rental SET rental_status = "rented" WHERE id = 59;
UPDATE book_rental SET rental_status = "rented" WHERE id = 60;
UPDATE book_rental SET rental_status = "rented" WHERE id = 61;
UPDATE book_rental SET rental_status = "returned" WHERE id = 62;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 425;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 63;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 64;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 64;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 2073;
UPDATE book_rental SET rental_status = "returned" WHERE id = 65;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1493;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 66;
UPDATE book_rental SET rental_status = "returned" WHERE id = 67;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1018;
UPDATE book_rental SET rental_status = "returned" WHERE id = 68;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1874;
UPDATE book_rental SET rental_status = "returned" WHERE id = 69;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 534;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 70;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 70;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 2340;
UPDATE book_rental SET rental_status = "rented" WHERE id = 71;
UPDATE book_rental SET rental_status = "rented" WHERE id = 72;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 73;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 73;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1171;
UPDATE book_rental SET rental_status = "returned" WHERE id = 74;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 2184;
UPDATE book_rental SET rental_status = "rented" WHERE id = 75;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 76;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 76;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 446;
UPDATE book_rental SET rental_status = "rented" WHERE id = 77;
UPDATE book_rental SET rental_status = "returned" WHERE id = 78;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1056;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 79;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 80;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 80;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1763;
UPDATE book_rental SET rental_status = "returned" WHERE id = 81;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 779;
UPDATE book_rental SET rental_status = "rented" WHERE id = 82;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 84;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 84;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 434;
UPDATE book_rental SET rental_status = "rented" WHERE id = 85;
UPDATE book_rental SET rental_status = "returned" WHERE id = 86;
UPDATE book_rental SET rental_status = "returned" WHERE id = 86;
UPDATE book_rental SET rental_status = "returned" WHERE id = 86;
UPDATE book_rental SET rental_status = "rented" WHERE id = 87;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 88;
UPDATE book_rental SET rental_status = "rented" WHERE id = 89;
UPDATE book_rental SET rental_status = "rented" WHERE id = 90;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 91;
UPDATE book_rental SET rental_status = "rented" WHERE id = 92;
UPDATE book_rental SET rental_status = "rented" WHERE id = 93;
UPDATE book_rental SET rental_status = "returned" WHERE id = 94;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1416;
UPDATE book_rental SET rental_status = "returned" WHERE id = 95;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1828;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 97;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 97;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 176;
UPDATE book_rental SET rental_status = "returned" WHERE id = 98;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1033;
UPDATE book_rental SET rental_status = "rented" WHERE id = 99;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 100;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 100;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 435;
UPDATE book_rental SET rental_status = "rented" WHERE id = 102;
UPDATE book_rental SET rental_status = "returned" WHERE id = 103;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 969;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 104;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 104;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1393;
UPDATE book_rental SET rental_status = "returned" WHERE id = 105;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 605;
UPDATE book_rental SET rental_status = "rented" WHERE id = 106;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 107;
UPDATE book_rental SET rental_status = "returned" WHERE id = 108;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 852;
UPDATE book_rental SET rental_status = "rented" WHERE id = 109;
UPDATE book_rental SET rental_status = "rented" WHERE id = 110;
UPDATE book_rental SET rental_status = "rented" WHERE id = 111;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 112;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 112;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 223;
UPDATE book_rental SET rental_status = "rented" WHERE id = 113;
UPDATE book_rental SET rental_status = "rented" WHERE id = 114;
UPDATE book_rental SET rental_status = "rented" WHERE id = 115;
UPDATE book_rental SET rental_status = "returned" WHERE id = 116;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 843;
UPDATE book_rental SET rental_status = "rented" WHERE id = 117;
UPDATE book_rental SET rental_status = "rented" WHERE id = 118;
UPDATE book_rental SET rental_status = "rented" WHERE id = 119;
UPDATE book_rental SET rental_status = "returned" WHERE id = 120;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 2327;
UPDATE book_rental SET rental_status = "rented" WHERE id = 121;
UPDATE book_rental SET rental_status = "rented" WHERE id = 122;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 123;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 123;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1283;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 124;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 124;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1549;
UPDATE book_rental SET rental_status = "rented" WHERE id = 125;
UPDATE book_rental SET rental_status = "returned" WHERE id = 126;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 911;
UPDATE book_rental SET rental_status = "rented" WHERE id = 127;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 128;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 129;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 129;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1009;
UPDATE book_rental SET rental_status = "rented" WHERE id = 130;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 131;
UPDATE book_rental SET rental_status = "rented" WHERE id = 132;
UPDATE book_rental SET rental_status = "rented" WHERE id = 133;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 134;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 134;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 2485;
UPDATE book_rental SET rental_status = "rented" WHERE id = 135;
UPDATE book_rental SET rental_status = "returned" WHERE id = 136;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1198;
UPDATE book_rental SET rental_status = "returned" WHERE id = 137;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1978;
UPDATE book_rental SET rental_status = "rented" WHERE id = 138;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 139;
UPDATE book_rental SET rental_status = "rented" WHERE id = 140;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 141;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 141;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1234;
UPDATE book_rental SET rental_status = "rented" WHERE id = 143;
UPDATE book_rental SET rental_status = "rented" WHERE id = 144;
UPDATE book_rental SET rental_status = "rented" WHERE id = 145;
UPDATE book_rental SET rental_status = "rented" WHERE id = 146;
UPDATE book_rental SET rental_status = "rented" WHERE id = 147;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 148;
UPDATE book_rental SET rental_status = "returned" WHERE id = 149;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 394;
UPDATE book_rental SET rental_status = "returned" WHERE id = 150;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1286;
UPDATE book_rental SET rental_status = "rented" WHERE id = 151;
UPDATE book_rental SET rental_status = "returned" WHERE id = 152;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1417;
UPDATE book_rental SET rental_status = "returned" WHERE id = 153;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1484;
UPDATE book_rental SET rental_status = "rented" WHERE id = 154;
UPDATE book_rental SET rental_status = "rented" WHERE id = 155;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 156;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 157;
UPDATE book_rental SET rental_status = "returned" WHERE id = 158;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 647;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 159;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 160;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 160;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 2479;
UPDATE book_rental SET rental_status = "rented" WHERE id = 161;
UPDATE book_rental SET rental_status = "returned" WHERE id = 162;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 2246;
UPDATE book_rental SET rental_status = "returned" WHERE id = 163;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 939;
UPDATE book_rental SET rental_status = "rented" WHERE id = 164;
UPDATE book_rental SET rental_status = "rented" WHERE id = 165;
UPDATE book_rental SET rental_status = "rented" WHERE id = 166;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 167;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 168;
UPDATE book_rental SET rental_status = "returned" WHERE id = 169;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1364;
UPDATE book_rental SET rental_status = "rented" WHERE id = 170;
UPDATE book_rental SET rental_status = "rented" WHERE id = 171;
UPDATE book_rental SET rental_status = "returned" WHERE id = 172;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1340;
UPDATE book_rental SET rental_status = "rented" WHERE id = 173;
UPDATE book_rental SET rental_status = "returned" WHERE id = 174;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 978;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 175;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 175;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1847;
UPDATE book_rental SET rental_status = "rented" WHERE id = 177;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 178;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 178;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1683;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 179;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 180;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 180;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 134;
UPDATE book_rental SET rental_status = "returned" WHERE id = 181;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 2456;
UPDATE book_rental SET rental_status = "rented" WHERE id = 182;
UPDATE book_rental SET rental_status = "rented" WHERE id = 183;
UPDATE book_rental SET rental_status = "rented" WHERE id = 184;
UPDATE book_rental SET rental_status = "returned" WHERE id = 185;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 662;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 186;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 186;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 390;
UPDATE book_rental SET rental_status = "rented" WHERE id = 187;
UPDATE book_rental SET rental_status = "returned" WHERE id = 188;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 597;
UPDATE book_rental SET rental_status = "returned" WHERE id = 189;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 587;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 190;
UPDATE book_rental SET rental_status = "returned" WHERE id = 191;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 814;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 192;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 192;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 2480;
UPDATE book_rental SET rental_status = "rented" WHERE id = 193;
UPDATE book_rental SET rental_status = "rented" WHERE id = 194;
UPDATE book_rental SET rental_status = "rented" WHERE id = 195;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 196;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 196;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1090;
UPDATE book_rental SET rental_status = "rented" WHERE id = 197;
UPDATE book_rental SET rental_status = "returned" WHERE id = 199;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1888;
UPDATE book_rental SET rental_status = "rented" WHERE id = 200;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 201;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 201;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1306;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 202;
UPDATE book_rental SET rental_status = "rented" WHERE id = 203;
UPDATE book_rental SET rental_status = "rented" WHERE id = 204;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 205;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 207;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 207;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 912;
UPDATE book_rental SET rental_status = "returned" WHERE id = 208;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 688;
UPDATE book_rental SET rental_status = "rented" WHERE id = 209;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 210;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 210;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 183;
UPDATE book_rental SET rental_status = "returned" WHERE id = 212;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 89;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 213;
UPDATE book_rental SET rental_status = "returned" WHERE id = 214;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 918;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 215;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 215;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1914;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 216;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 216;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 30;
UPDATE book_rental SET rental_status = "rented" WHERE id = 218;
UPDATE book_rental SET rental_status = "rented" WHERE id = 219;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 220;
UPDATE book_rental SET rental_status = "rented" WHERE id = 221;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 222;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 222;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 92;
UPDATE book_rental SET rental_status = "rented" WHERE id = 223;
UPDATE book_rental SET rental_status = "rented" WHERE id = 225;
UPDATE book_rental SET rental_status = "rented" WHERE id = 226;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 227;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 227;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 879;
UPDATE book_rental SET rental_status = "returned" WHERE id = 228;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 1010;
UPDATE book_rental SET rental_status = "reservation" WHERE id = 229;
UPDATE book_rental SET rental_status = "returned" WHERE id = 230;
UPDATE book_copies_per_school SET availability = "1" WHERE id = 519;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 231;
UPDATE book_rental SET rental_status = "cancelled" WHERE id = 231;
UPDATE book_copies_per_school SET availability = 1 WHERE id = 1276;
