INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (41, 7, 763, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 763;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 7, 1845, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1845;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (59, 7, 2201, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2201;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (109, 7, 1339, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1339;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (7, 8, 1891, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1891;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (77, 8, 1874, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1874;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (53, 8, 1785, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1785;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (23, 8, 1206, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1206;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (16, 9, 1695, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1695;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (42, 9, 2383, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2383;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (11, 9, 1170, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1170;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (23, 9, 1213, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1213;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (22, 10, 1119, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1119;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (84, 10, 647, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 647;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (96, 10, 621, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 621;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (85, 10, 349, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 349;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (7, 11, 1915, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1915;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (92, 11, 890, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 890;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (50, 11, 446, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 446;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (95, 11, 1484, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1484;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (43, 12, 2086, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2086;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (105, 12, 1193, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1193;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (99, 12, 2342, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2342;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (77, 12, 1886, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1886;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (92, 13, 886, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 886;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 13, 1846, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1846;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (35, 13, 2148, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2148;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (107, 13, 2250, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2250;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (46, 14, 2115, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2115;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (109, 14, 1351, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1351;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (102, 14, 566, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 566;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (53, 14, 1786, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1786;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (18, 15, 1135, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1135;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (102, 15, 571, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 571;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (107, 15, 2259, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2259;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (94, 15, 96, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 96;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (109, 16, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (47, 16, 2102, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2102;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (46, 16, 2135, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2135;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (7, 16, 1913, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1913;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (66, 17, 419, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 419;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (52, 17, 843, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 843;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (56, 17, 1275, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1275;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (108, 17, 1416, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1416;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (77, 18, 1887, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1887;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (89, 18, 1286, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1286;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (46, 19, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (8, 19, 790, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 790;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (29, 19, 486, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 486;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (56, 19, 1246, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1246;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (74, 20, 2238, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2238;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (68, 20, 372, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 372;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (17, 20, 1549, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1549;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (108, 20, 1426, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1426;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (116, 21, 64, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 64;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (97, 21, 1033, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1033;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (45, 21, 2014, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2014;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (84, 21, 652, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 652;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (22, 22, 1127, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1127;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (85, 22, 325, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 325;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (81, 22, 246, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 246;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (113, 22, 1387, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1387;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (86, 23, 692, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 692;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (107, 23, 2279, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2279;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (70, 23, 358, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 358;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (38, 23, 961, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 961;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (95, 24, 1508, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1508;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (11, 24, 1160, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1160;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (97, 24, 1011, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1011;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (41, 24, 755, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 755;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (86, 25, 693, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 693;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (94, 25, 106, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 106;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (69, 25, 162, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 162;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (106, 25, 1575, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1575;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (69, 26, 152, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 152;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (34, 26, 742, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 742;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (111, 26, 1399, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1399;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (63, 27, 1978, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1978;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (46, 27, 2128, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2128;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (42, 27, 2397, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2397;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (89, 27, 1289, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1289;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (34, 28, 707, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 707;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (71, 28, 2439, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2439;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (84, 28, 653, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 653;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (12, 28, 918, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 918;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (80, 29, 2286, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2286;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (74, 29, 2246, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2246;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (56, 29, 1247, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1247;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (87, 29, 1755, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1755;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (22, 30, 1096, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1096;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (1, 30, 2162, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2162;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (39, 30, 2486, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2486;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (112, 30, 1713, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1713;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (69, 31, 153, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 153;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (10, 31, 1470, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1470;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (116, 31, 39, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 39;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (71, 31, 2438, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2438;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (48, 32, 1535, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1535;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (46, 32, 2136, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2136;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (75, 32, 323, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 323;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (87, 32, 1752, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1752;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (111, 33, 1393, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1393;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (84, 33, 648, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 648;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (22, 33, 1120, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1120;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (107, 33, 2260, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2260;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (90, 34, 1638, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1638;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (38, 34, 958, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 958;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (77, 34, 1875, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1875;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (106, 34, 1563, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1563;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (43, 35, 2087, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2087;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (80, 35, 2284, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2284;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (69, 36, 154, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 154;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (38, 36, 957, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 957;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (87, 36, 1767, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1767;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (33, 37, 992, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 992;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (44, 37, 2051, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2051;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (78, 37, 231, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 231;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (12, 37, 919, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 919;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (72, 38, 1055, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1055;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (63, 38, 1979, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1979;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (89, 38, 1290, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1290;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (9, 38, 523, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 523;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (44, 39, 2062, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2062;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (11, 39, 1161, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1161;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (52, 40, 838, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 838;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (44, 40, 2073, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2073;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (53, 40, 1793, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1793;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (29, 40, 498, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 498;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (10, 41, 1471, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1471;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (57, 41, 425, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 425;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (112, 41, 1725, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1725;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (64, 41, 1600, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1600;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (96, 42, 622, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 622;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (27, 42, 2310, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2310;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (30, 42, 284, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 284;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (86, 42, 687, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 687;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (72, 43, 1067, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1067;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (101, 43, 29, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 29;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (18, 43, 1155, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1155;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (30, 44, 270, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 270;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (89, 44, 1297, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1297;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (87, 44, 1756, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1756;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (21, 44, 1073, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1073;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (23, 45, 1214, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1214;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (52, 45, 839, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 839;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (43, 45, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (36, 45, 1963, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1963;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (43, 46, 2088, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2088;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (111, 46, "on hold", 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (28, 46, 519, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 519;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 46, 1827, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1827;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (95, 46, 1485, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1485;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (41, 47, 764, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 764;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (50, 47, 433, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 433;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (97, 47, 1034, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1034;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (14, 48, 947, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 947;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (74, 48, 2239, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2239;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (97, 48, 1017, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1017;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (89, 48, 1291, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1291;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (113, 49, 1368, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1368;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (89, 49, 1298, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1298;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (111, 49, 1408, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1408;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (82, 49, 662, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 662;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (52, 50, 840, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 840;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (30, 50, 308, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 308;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (39, 51, 2485, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2485;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (64, 51, 1601, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1601;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (113, 51, 1388, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1388;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (7, 52, 1914, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1914;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (84, 52, 654, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 654;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (22, 52, 1108, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1108;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (48, 52, 1536, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1536;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (9, 53, 524, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 524;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (20, 53, 1672, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1672;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (45, 53, 2039, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2039;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (78, 53, 219, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 219;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (17, 54, 1550, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1550;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (102, 54, 567, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 567;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (73, 54, 1009, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1009;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (9, 54, 534, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 534;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (82, 55, 673, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 673;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (38, 55, 962, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 962;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (20, 56, 1669, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1669;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (29, 56, 506, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 506;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (118, 57, 1332, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1332;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 57, 1831, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1831;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (63, 58, 1993, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1993;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (48, 58, 1537, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1537;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (101, 59, 1, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (102, 59, 568, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 568;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (23, 60, 1215, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1215;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (108, 60, 1440, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1440;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (94, 61, 115, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 115;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (78, 61, 212, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 212;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (119, 62, 1707, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1707;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (60, 62, 2364, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2364;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (38, 63, 969, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 969;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (102, 63, 572, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 572;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (66, 64, 389, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 389;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (33, 64, 996, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 996;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (60, 65, 2358, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2358;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (18, 65, 1145, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1145;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (111, 66, "on hold", 2);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (57, 66, 426, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 426;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (120, 66, 2420, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2420;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (25, 67, 1847, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1847;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (60, 67, 2365, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2365;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (74, 68, 2240, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2240;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (62, 68, 423, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 423;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (41, 69, 756, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 756;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (113, 69, 1369, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1369;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority) VALUES (109, 70, "on hold", 2);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (42, 70, 2409, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2409;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (71, 70, 2440, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2440;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (94, 71, 107, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 107;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (48, 71, 1543, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1543;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (7, 72, 1906, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1906;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (22, 72, 1121, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1121;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (44, 73, 2063, "rented");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2063;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (2, 73, 189, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 189;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status) VALUES (27, 74, 2320, "reservation");
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2320;
UPDATE book_rental SET rental_status = "rented" WHERE id = 1;UPDATE book_rental SET rental_status = "rented" WHERE id = 2;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 3;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 3;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 2201;UPDATE book_rental SET rental_status = "rented" WHERE id = 4;UPDATE book_rental SET rental_status = "rented" WHERE id = 5;UPDATE book_rental SET rental_status = "rented" WHERE id = 6;UPDATE book_rental SET rental_status = "rented" WHERE id = 7;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 8;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 8;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1206;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 9;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 9;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1695;UPDATE book_rental SET rental_status = "returned" WHERE id = 10;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2383;UPDATE book_rental SET rental_status = "rented" WHERE id = 11;UPDATE book_rental SET rental_status = "rented" WHERE id = 12;UPDATE book_rental SET rental_status = "reservation" WHERE id = 13;UPDATE book_rental SET rental_status = "returned" WHERE id = 14;UPDATE book_copies_per_school SET availability = "1" WHERE id = 647;UPDATE book_rental SET rental_status = "reservation" WHERE id = 15;UPDATE book_rental SET rental_status = "returned" WHERE id = 16;UPDATE book_copies_per_school SET availability = "1" WHERE id = 349;UPDATE book_rental SET rental_status = "rented" WHERE id = 17;UPDATE book_rental SET rental_status = "rented" WHERE id = 18;UPDATE book_rental SET rental_status = "returned" WHERE id = 19;UPDATE book_copies_per_school SET availability = "1" WHERE id = 446;UPDATE book_rental SET rental_status = "rented" WHERE id = 20;UPDATE book_rental SET rental_status = "rented" WHERE id = 21;UPDATE book_rental SET rental_status = "rented" WHERE id = 22;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 23;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 23;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 2342;UPDATE book_rental SET rental_status = "rented" WHERE id = 24;UPDATE book_rental SET rental_status = "rented" WHERE id = 25;UPDATE book_rental SET rental_status = "rented" WHERE id = 26;UPDATE book_rental SET rental_status = "reservation" WHERE id = 27;UPDATE book_rental SET rental_status = "rented" WHERE id = 28;UPDATE book_rental SET rental_status = "returned" WHERE id = 29;UPDATE book_rental SET rental_status = "returned" WHERE id = 30;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1351;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 31;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 31;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 566;UPDATE book_rental SET rental_status = "rented" WHERE id = 32;UPDATE book_rental SET rental_status = "reservation" WHERE id = 33;UPDATE book_rental SET rental_status = "returned" WHERE id = 34;UPDATE book_copies_per_school SET availability = "1" WHERE id = 571;UPDATE book_rental SET rental_status = "returned" WHERE id = 35;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2259;UPDATE book_rental SET rental_status = "rented" WHERE id = 36;UPDATE book_rental SET rental_status = "returned" WHERE id = 38;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2102;UPDATE book_rental SET rental_status = "rented" WHERE id = 39;UPDATE book_rental SET rental_status = "rented" WHERE id = 40;UPDATE book_rental SET rental_status = "rented" WHERE id = 41;UPDATE book_rental SET rental_status = "reservation" WHERE id = 42;UPDATE book_rental SET rental_status = "rented" WHERE id = 43;UPDATE book_rental SET rental_status = "returned" WHERE id = 44;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1416;UPDATE book_rental SET rental_status = "rented" WHERE id = 45;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 46;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 46;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1286;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 48;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 48;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 790;UPDATE book_rental SET rental_status = "rented" WHERE id = 49;UPDATE book_rental SET rental_status = "rented" WHERE id = 50;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 51;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 51;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 2238;UPDATE book_rental SET rental_status = "rented" WHERE id = 52;UPDATE book_rental SET rental_status = "returned" WHERE id = 53;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1549;UPDATE book_rental SET rental_status = "returned" WHERE id = 54;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1426;UPDATE book_rental SET rental_status = "reservation" WHERE id = 55;UPDATE book_rental SET rental_status = "rented" WHERE id = 56;UPDATE book_rental SET rental_status = "rented" WHERE id = 57;UPDATE book_rental SET rental_status = "rented" WHERE id = 58;UPDATE book_rental SET rental_status = "rented" WHERE id = 59;UPDATE book_rental SET rental_status = "returned" WHERE id = 60;UPDATE book_copies_per_school SET availability = "1" WHERE id = 325;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 61;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 61;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 246;UPDATE book_rental SET rental_status = "rented" WHERE id = 62;UPDATE book_rental SET rental_status = "returned" WHERE id = 63;UPDATE book_copies_per_school SET availability = "1" WHERE id = 692;UPDATE book_rental SET rental_status = "rented" WHERE id = 64;UPDATE book_rental SET rental_status = "reservation" WHERE id = 65;UPDATE book_rental SET rental_status = "returned" WHERE id = 66;UPDATE book_copies_per_school SET availability = "1" WHERE id = 961;UPDATE book_rental SET rental_status = "rented" WHERE id = 67;UPDATE book_rental SET rental_status = "returned" WHERE id = 68;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1160;UPDATE book_rental SET rental_status = "rented" WHERE id = 69;UPDATE book_rental SET rental_status = "rented" WHERE id = 70;UPDATE book_rental SET rental_status = "rented" WHERE id = 71;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 72;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 72;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 106;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 73;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 73;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 162;UPDATE book_rental SET rental_status = "returned" WHERE id = 74;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1575;UPDATE book_rental SET rental_status = "reservation" WHERE id = 75;UPDATE book_rental SET rental_status = "rented" WHERE id = 76;UPDATE book_rental SET rental_status = "reservation" WHERE id = 77;UPDATE book_rental SET rental_status = "rented" WHERE id = 78;UPDATE book_rental SET rental_status = "rented" WHERE id = 79;UPDATE book_rental SET rental_status = "returned" WHERE id = 80;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2397;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 81;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 81;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1289;UPDATE book_rental SET rental_status = "reservation" WHERE id = 82;UPDATE book_rental SET rental_status = "rented" WHERE id = 83;UPDATE book_rental SET rental_status = "rented" WHERE id = 84;UPDATE book_rental SET rental_status = "returned" WHERE id = 85;UPDATE book_copies_per_school SET availability = "1" WHERE id = 918;UPDATE book_rental SET rental_status = "reservation" WHERE id = 86;UPDATE book_rental SET rental_status = "rented" WHERE id = 87;UPDATE book_rental SET rental_status = "rented" WHERE id = 88;UPDATE book_rental SET rental_status = "reservation" WHERE id = 89;UPDATE book_rental SET rental_status = "returned" WHERE id = 90;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1096;UPDATE book_rental SET rental_status = "returned" WHERE id = 91;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2162;UPDATE book_rental SET rental_status = "reservation" WHERE id = 92;UPDATE book_rental SET rental_status = "rented" WHERE id = 93;UPDATE book_rental SET rental_status = "returned" WHERE id = 94;UPDATE book_copies_per_school SET availability = "1" WHERE id = 153;UPDATE book_rental SET rental_status = "rented" WHERE id = 95;UPDATE book_rental SET rental_status = "returned" WHERE id = 96;UPDATE book_copies_per_school SET availability = "1" WHERE id = 39;UPDATE book_rental SET rental_status = "reservation" WHERE id = 97;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 98;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 98;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1535;UPDATE book_rental SET rental_status = "returned" WHERE id = 99;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2136;UPDATE book_rental SET rental_status = "rented" WHERE id = 100;UPDATE book_rental SET rental_status = "rented" WHERE id = 101;UPDATE book_rental SET rental_status = "returned" WHERE id = 102;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1393;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 103;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 103;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 648;UPDATE book_rental SET rental_status = "rented" WHERE id = 104;UPDATE book_rental SET rental_status = "returned" WHERE id = 105;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2260;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 106;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 106;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1638;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 107;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 107;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 958;UPDATE book_rental SET rental_status = "rented" WHERE id = 108;UPDATE book_rental SET rental_status = "rented" WHERE id = 109;UPDATE book_rental SET rental_status = "rented" WHERE id = 110;UPDATE book_rental SET rental_status = "rented" WHERE id = 111;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 112;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 112;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 154;UPDATE book_rental SET rental_status = "reservation" WHERE id = 113;UPDATE book_rental SET rental_status = "returned" WHERE id = 114;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1767;UPDATE book_rental SET rental_status = "rented" WHERE id = 115;UPDATE book_rental SET rental_status = "returned" WHERE id = 116;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2051;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 117;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 117;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 231;UPDATE book_rental SET rental_status = "returned" WHERE id = 118;UPDATE book_copies_per_school SET availability = "1" WHERE id = 919;UPDATE book_rental SET rental_status = "returned" WHERE id = 119;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1055;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 120;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 120;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1979;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 121;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 121;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1290;UPDATE book_rental SET rental_status = "returned" WHERE id = 122;UPDATE book_copies_per_school SET availability = "1" WHERE id = 523;UPDATE book_rental SET rental_status = "returned" WHERE id = 123;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2062;UPDATE book_rental SET rental_status = "rented" WHERE id = 124;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 125;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 125;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 838;UPDATE book_rental SET rental_status = "rented" WHERE id = 126;UPDATE book_rental SET rental_status = "reservation" WHERE id = 127;UPDATE book_rental SET rental_status = "returned" WHERE id = 128;UPDATE book_copies_per_school SET availability = "1" WHERE id = 498;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 129;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 129;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1471;UPDATE book_rental SET rental_status = "rented" WHERE id = 130;UPDATE book_rental SET rental_status = "reservation" WHERE id = 131;UPDATE book_rental SET rental_status = "rented" WHERE id = 132;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 133;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 133;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 622;UPDATE book_rental SET rental_status = "returned" WHERE id = 134;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2310;UPDATE book_rental SET rental_status = "rented" WHERE id = 135;UPDATE book_rental SET rental_status = "returned" WHERE id = 136;UPDATE book_copies_per_school SET availability = "1" WHERE id = 687;UPDATE book_rental SET rental_status = "reservation" WHERE id = 137;UPDATE book_rental SET rental_status = "reservation" WHERE id = 138;UPDATE book_rental SET rental_status = "rented" WHERE id = 139;UPDATE book_rental SET rental_status = "rented" WHERE id = 140;UPDATE book_rental SET rental_status = "rented" WHERE id = 141;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 142;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 142;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1756;UPDATE book_rental SET rental_status = "rented" WHERE id = 143;UPDATE book_rental SET rental_status = "returned" WHERE id = 144;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1214;UPDATE book_rental SET rental_status = "rented" WHERE id = 145;UPDATE book_rental SET rental_status = "reservation" WHERE id = 147;UPDATE book_rental SET rental_status = "rented" WHERE id = 148;UPDATE book_rental SET rental_status = "returned" WHERE id = 150;UPDATE book_copies_per_school SET availability = "1" WHERE id = 519;UPDATE book_rental SET rental_status = "rented" WHERE id = 151;UPDATE book_rental SET rental_status = "reservation" WHERE id = 152;UPDATE book_rental SET rental_status = "rented" WHERE id = 153;UPDATE book_rental SET rental_status = "returned" WHERE id = 154;UPDATE book_copies_per_school SET availability = "1" WHERE id = 433;UPDATE book_rental SET rental_status = "reservation" WHERE id = 155;UPDATE book_rental SET rental_status = "reservation" WHERE id = 156;UPDATE book_rental SET rental_status = "returned" WHERE id = 157;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2239;UPDATE book_rental SET rental_status = "rented" WHERE id = 158;UPDATE book_rental SET rental_status = "returned" WHERE id = 159;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1291;UPDATE book_rental SET rental_status = "rented" WHERE id = 160;UPDATE book_rental SET rental_status = "returned" WHERE id = 161;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1298;UPDATE book_rental SET rental_status = "returned" WHERE id = 162;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1408;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 163;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 163;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 662;UPDATE book_rental SET rental_status = "returned" WHERE id = 164;UPDATE book_copies_per_school SET availability = "1" WHERE id = 840;UPDATE book_rental SET rental_status = "rented" WHERE id = 165;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 166;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 166;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 2485;UPDATE book_rental SET rental_status = "rented" WHERE id = 167;UPDATE book_rental SET rental_status = "returned" WHERE id = 168;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1388;UPDATE book_rental SET rental_status = "reservation" WHERE id = 169;UPDATE book_rental SET rental_status = "rented" WHERE id = 170;UPDATE book_rental SET rental_status = "rented" WHERE id = 171;UPDATE book_rental SET rental_status = "returned" WHERE id = 172;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1536;UPDATE book_rental SET rental_status = "rented" WHERE id = 173;UPDATE book_rental SET rental_status = "rented" WHERE id = 174;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 175;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 175;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 2039;UPDATE book_rental SET rental_status = "rented" WHERE id = 176;UPDATE book_rental SET rental_status = "returned" WHERE id = 177;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1550;UPDATE book_rental SET rental_status = "rented" WHERE id = 178;UPDATE book_rental SET rental_status = "returned" WHERE id = 179;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1009;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 180;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 180;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 534;UPDATE book_rental SET rental_status = "rented" WHERE id = 181;UPDATE book_rental SET rental_status = "rented" WHERE id = 182;UPDATE book_rental SET rental_status = "returned" WHERE id = 183;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1669;UPDATE book_rental SET rental_status = "rented" WHERE id = 184;UPDATE book_rental SET rental_status = "returned" WHERE id = 185;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1332;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 186;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 186;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 1831;UPDATE book_rental SET rental_status = "rented" WHERE id = 187;UPDATE book_rental SET rental_status = "reservation" WHERE id = 188;UPDATE book_rental SET rental_status = "rented" WHERE id = 189;UPDATE book_rental SET rental_status = "rented" WHERE id = 190;UPDATE book_rental SET rental_status = "rented" WHERE id = 191;UPDATE book_rental SET rental_status = "rented" WHERE id = 192;UPDATE book_rental SET rental_status = "returned" WHERE id = 193;UPDATE book_copies_per_school SET availability = "1" WHERE id = 115;UPDATE book_rental SET rental_status = "rented" WHERE id = 194;UPDATE book_rental SET rental_status = "returned" WHERE id = 195;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1707;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 196;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 196;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 2364;UPDATE book_rental SET rental_status = "rented" WHERE id = 197;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 198;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 198;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 572;UPDATE book_rental SET rental_status = "reservation" WHERE id = 199;UPDATE book_rental SET rental_status = "rented" WHERE id = 200;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 201;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 201;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 2358;UPDATE book_rental SET rental_status = "returned" WHERE id = 202;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1145;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 204;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 204;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 426;UPDATE book_rental SET rental_status = "rented" WHERE id = 205;UPDATE book_rental SET rental_status = "returned" WHERE id = 206;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1847;UPDATE book_rental SET rental_status = "reservation" WHERE id = 207;UPDATE book_rental SET rental_status = "returned" WHERE id = 208;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2240;UPDATE book_rental SET rental_status = "rented" WHERE id = 209;UPDATE book_rental SET rental_status = "rented" WHERE id = 210;UPDATE book_rental SET rental_status = "rented" WHERE id = 211;UPDATE book_rental SET rental_status = "reservation" WHERE id = 213;UPDATE book_rental SET rental_status = "returned" WHERE id = 214;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2440;UPDATE book_rental SET rental_status = "rented" WHERE id = 215;UPDATE book_rental SET rental_status = "returned" WHERE id = 216;UPDATE book_copies_per_school SET availability = "1" WHERE id = 1543;UPDATE book_rental SET rental_status = "rented" WHERE id = 217;UPDATE book_rental SET rental_status = "rented" WHERE id = 218;UPDATE book_rental SET rental_status = "returned" WHERE id = 219;UPDATE book_copies_per_school SET availability = "1" WHERE id = 2063;UPDATE book_rental SET rental_status = "cancelled" WHERE id = 220;UPDATE book_rental                                       SET rental_status = "cancelled"                                       WHERE id = 220;UPDATE book_copies_per_school                                        SET availability = 1                                        WHERE id = 189;UPDATE book_rental SET rental_status = "reservation" WHERE id = 221;