INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (47, 7, "5", "Insight Guide -Puerto Rico", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (47, 7, "5", "A super favorite!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (24, 7, "4", "Nudity of the finest quality", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (119, 7, "5", "Very Enjoyable", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (48, 7, "5", "Beutifully written and inspiring", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (51, 7, "2", "Ghastly", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (109, 7, "2", "Disappointing", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (103, 7, "5", "A great book about the middle ages", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (104, 8, "5", "=]", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (114, 8, "4", "Paula Deen-Great as Usual", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (104, 8, "3", "Narrow focus keeps things dull", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (111, 8, "3", "Changed", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (27, 8, "5", "Great book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (44, 9, "4", "A Good Read!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (8, 9, "1", "Christian Couselors Manual", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (22, 9, "5", "I didnt enjoy this book as much Hunger or Growth of the Soil, but it was still very interesting.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (20, 10, "5", "Dynamic--The DSS Are Awesome", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (30, 10, "5", "For Those Who Have Fallen In Love With IG Breed", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (30, 10, "5", "EXCELLENT", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (42, 10, "2", "Makes growing grass seem fast paced.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (14, 10, "1", "Errors flaw this review of the EO Church", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (95, 10, "5", "The Fire Still Burns", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (56, 10, "1", "Daughter of Fortune", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (105, 10, "5", "best of all the books", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (8, 10, "5", "The Wonderful World of Little Women", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (93, 10, "5", "It is very interesting", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (109, 11, "2", "Good Start But Limited Detail on the Defense of the Bridges on D-day", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (85, 12, "5", "A Touching Classic", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (111, 12, "5", "I like this Biology Book.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (69, 12, "5", "Smooth and feminine", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (84, 13, "5", "A different approach", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (16, 13, "4", "Yours is the Earth", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (59, 13, "5", "This book is a sheer jewel", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (84, 15, "5", "A classic tale of greed and redemption.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (118, 15, "1", "Gun Man changes thelives of the Family", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (44, 16, "5", "Killing Floor", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (34, 16, "5", "Lynch Mob Justice Then and Now", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (52, 17, "4", "These books focus on what might seem like narrow topics, but", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (104, 17, "4", "Hard to get into; but once you do, its very good", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (38, 18, "4", "Great Map and Great Resource", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (43, 18, "5", "The great American novel", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (53, 18, "5", "Awesome Tale!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (102, 18, "5", "My Home Town", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (77, 18, "5", "wonderful book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (2, 18, "4", "great poetry, great artwork, great fathers", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (22, 19, "5", "interesting look at concepts of power and exchange", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (18, 20, "5", "As a support person...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (74, 20, "5", "Excellent Book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (34, 20, "5", "best book ever", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (38, 20, "4", "With a twist", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (63, 21, "4", "Steinbecks voice for the Depression generation remains preeminent", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (97, 21, "4", "Keen perceptions", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (60, 21, "5", "Review from a book lover", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (16, 21, "5", "Comments on Carey 2007", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (109, 22, "5", "Wonderful", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (111, 22, "1", "So glad this was given to me, and I DIDNT waste money on it.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (64, 22, "5", "The Pleasures of Reading the Intimate Henry James", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (60, 23, "5", "Its GREAT", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (98, 23, "4", "A good book, more about personal experiences than about tactics", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (44, 23, "1", "Annoying", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (30, 23, "4", "most interesting", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (98, 25, "5", "A real eye-opener", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (92, 25, "5", "Best Villian", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (32, 25, "5", "review of Chaim Potoks &quot;I am the Clay&quot", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (72, 26, "5", "The book that turned me into an author...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (66, 26, "5", "Most inflential book Ive ever read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (63, 26, "5", "A beautiful, moving book that has withstood the test of time", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (93, 26, "4", "U.S. Deep Penetration Operations in Burma", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (85, 26, "5", "Brings the Forbidden City to life", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (112, 26, "5", "An origional Agatha Christie book!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (113, 26, "5", "Speechless", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (22, 27, "2", "Blatant RIP-OFF of Body-for-Life!!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (102, 28, "5", "Awesome!!!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (50, 28, "5", "The Best Book Ever Written.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (24, 28, "5", "Excellent!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (111, 28, "5", "If you like the show, youll probably like the book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (72, 28, "5", "Fabulous Read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (97, 28, "5", "Wonderful.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (71, 28, "4", "Story redeems itself by the end", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (66, 29, "5", "priceless", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (8, 29, "5", "In the same genre as Harry Potter", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (82, 29, "5", "Creative way to teach the readings", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (17, 29, "5", "State of the Nation", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (53, 31, "5", "One of her best", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (85, 31, "5", "Awesome Book!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (113, 31, "5", "A beloved classic", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (108, 31, "5", "Best in the series!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (34, 31, "5", "cute, n clever.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (118, 31, "5", "Powerfully edifying!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (28, 31, "4", "enjoyed reading", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (2, 32, "4", "Good Read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (34, 32, "5", "Get ready to know the generals", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (7, 33, "5", "Photographs of Many American Cities", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (62, 33, "4", "Another almost-perfect Sarah Brandt mystery", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (99, 34, "4", "It was a great adventure book for all young readers", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (25, 34, "3", "Good, but lots of flaws in the writing", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (101, 34, "4", "A fascinating read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (104, 34, "4", "I still refer to the previous edition", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (114, 34, "5", "The apex of Perns saga", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (95, 35, "5", "A Superhuman Epic of Magic and Passion", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (95, 35, "3", "So teach me", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (60, 35, "5", "Journey with a classic", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (66, 35, "2", "Another typical Oprah pick", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (81, 35, "5", "Touching Story of Freindship", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (78, 36, "5", "Incredible", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (4, 36, "5", "My favourite of all the dark hunter novels so far...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (101, 36, "5", "An original, impressive, scholarly, informative study.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (109, 37, "5", "Awsome!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (49, 37, "5", "a more than pleasing whole", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (92, 37, "5", "Split", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (48, 37, "5", "This is a really great book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (50, 37, "5", "Great Book for beginners!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (24, 37, "5", "Amazing results!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (71, 37, "5", "A flexable blade of grass in a forest of brittle sticks", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (59, 37, "5", "An essential piece", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (56, 38, "3", "Oh, my God....", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (73, 38, "4", "The boomers are making cosmetic surgery boom", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (66, 38, "5", "Holes.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (74, 38, "5", "A Beautiful Explication of the Apostles Creed", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (60, 38, "5", "Its a key to the most exciting new world ever known!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (66, 39, "5", "The Federalist Papers (Signet Classics)", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (23, 39, "4", "a prophetic journey", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (41, 39, "5", "At last Capt. Burton comes alive", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (99, 39, "5", "Lots of info", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (87, 39, "5", "Riveting and well researched", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (18, 39, "5", "Best foaling book available!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (60, 39, "1", "Not really worth it.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (69, 40, "5", "Simply amazing novel", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (29, 40, "1", "One Star for Amazon!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (118, 40, "4", "Review of Night", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (23, 40, "5", "Doubleplusgood Book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (118, 40, "5", "The Fight Against the Leftist Historical Bias", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (74, 40, "4", "The Hobbit-Revisited", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (63, 40, "4", "The Bush Dyslexicon: Duh!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (70, 40, "5", "Great Read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (64, 41, "5", "great book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (4, 41, "1", "Jumped the Shark...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (71, 41, "5", "Masterly, a must read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (59, 41, "1", "Cook does Jules Verne", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (30, 41, "5", "Down Under by Bill Bryson", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (65, 42, "5", "Superb book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (103, 42, "5", "Liberty based on utilitarianism rather than human rights", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (62, 42, "4", "Its Good, But Sappy At Times!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (27, 42, "5", "Power of the feminine", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (116, 42, "4", "A very useful read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (71, 42, "4", "A great classic", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (93, 42, "5", "Cool Book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (69, 42, "5", "Conneticut Yankee Big Hit, Twain has done it again!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (107, 43, "5", "Sense and Sensibility", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (24, 43, "2", "A Made For TV Movie", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (116, 43, "5", "I LOVE THIS BOOK", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (45, 43, "5", "Misery By Stephen King", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (25, 44, "5", "Im Loving it!!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (2, 44, "5", "This is a story that I have many fond memories of.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (41, 44, "4", "Cool book!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (108, 44, "5", "Rankin at his finest", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (115, 44, "5", "Necessary!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (114, 44, "4", "Nice selection of recipes, Handy tips, Well written book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (60, 44, "5", "Every Fantasy Football Junkie should have this", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (18, 44, "5", "Great, Easy-to-Read Book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (56, 44, "5", "All time classic written by the most skilled SciFi author of our generation", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (109, 44, "5", "Back to Center", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (77, 45, "5", "One of Mitchener`s finest!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (36, 45, "4", "An stupendous achievement, not to be taken too seriously...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (20, 46, "2", "Useful but Potentially Unbalanced View of Workplace Ministry", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (25, 46, "5", "A work of art", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (20, 46, "5", "The best", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (11, 46, "4", "intriquing hero", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (34, 46, "5", "An absolute gem!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (29, 47, "5", "Paranormal", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (24, 47, "5", "There is much to learn from this book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (47, 47, "5", "You will Be in for a shock.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (50, 47, "5", "Extremely helpful and practical", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (111, 47, "4", "highly recommended", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (16, 47, "4", "Maybe 4+", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (102, 48, "5", "Excellent! One of the best books Ive ever read!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (53, 48, "5", "a beautiful edition for fans", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (4, 48, "5", "Heart-warming story about a girl named Rebecca", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (27, 48, "5", "Fantastic Work of Historical Research!! Wow!!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (112, 48, "4", "Prairie School but not necessarily Prairie Style", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (85, 48, "4", "&quot;I suppose they will all want dignity.&quot", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (36, 49, "5", "Absolutely wonderful", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (36, 49, "4", "Walking the Walk", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (44, 49, "5", "The Charm of a Trickster...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (90, 49, "1", "Strange Format", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (107, 49, "5", "One of the best stories Ive ever read...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (2, 49, "4", "Great Characters and Lots of Plot Twists - a la Christie!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (73, 49, "1", "Did He have an editor?", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (92, 49, "5", "Excellent edition of Einsteins Relativity", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (18, 49, "2", "There are better resources out there...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (71, 49, "1", "Audio Track is too quiet", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (60, 50, "5", "Very good book to get you out of the 9-to-5 routine", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (81, 50, "5", "Great Book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (99, 50, "5", "It Ends at the Blitz", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (86, 50, "5", "Smart and thoughtful writing", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (70, 50, "4", "Interesting comparisons on military strategy", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (36, 50, "5", "A very angry author pens out brilliance", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (98, 50, "5", "As the Title Says, Good Beginning Book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (25, 50, "5", "Must read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (22, 50, "3", "Brave New World", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (2, 50, "1", "What was Oprah thinking?", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (11, 51, "4", "Quite Real", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (38, 51, "5", "what an autobiography should be", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (13, 51, "5", "Great read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (93, 51, "5", "I like Mormons", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (112, 51, "5", "Takes the Tux off the bull", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (57, 51, "5", "BEST DANELLE STEELE EVER!!!!!!!!!!!!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (34, 51, "5", "Classic WEB Griffin", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (49, 51, "5", "A good long read.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (43, 51, "5", "profoundly gorgeous", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (77, 52, "5", "A MUST READ!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (111, 52, "5", "Excellent Book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (33, 52, "5", "Wow...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (45, 52, "5", "Great novellas in the Ender series!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (95, 53, "4", "a surrender to the moon", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (108, 53, "5", "One of the greatest fantasy series I have ever read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (27, 53, "5", "Somebodys got be on top", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (90, 53, "1", "God Awful", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (97, 53, "5", "Read the book, then see the movie", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (30, 54, "5", "Fantastic", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (80, 55, "3", "Lovin the Tyler Series", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (43, 55, "5", "Rich in information, hard to put down.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (50, 57, "5", "Brooks best work.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (29, 57, "3", "Wheres the Action???", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (56, 57, "5", "Sarks New Creative Companion", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (9, 57, "5", "Timeless", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (50, 57, "2", "AVID FAN DISAPOINTED", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (102, 57, "5", "A Funny Foursome", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (98, 57, "5", "Absolutely FULL of Camping Info.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (32, 57, "5", "Hot & Sexy", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (75, 58, "5", "History of Secret Societies", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (48, 58, "3", "Commendable Effort", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (7, 58, "5", "Informative", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (119, 58, "5", "A Long Title for a Good Book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (105, 59, "5", "The Lion The Wich and the Wardrobe get this book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (17, 59, "4", "Much better than the first!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (9, 59, "5", "This is the best!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (34, 59, "5", "Pride and Prejudice", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (115, 59, "5", "Worth the time it takes to read", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (92, 59, "4", "Unusual, sensational", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (18, 59, "5", "Like Plays of Old", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (107, 60, "5", "Zelaznys greatest achievement.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (106, 60, "5", "True Christianity returns to the mainstream. Thank you, Jim Wallis!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (43, 60, "4", "Livin in tha Fat Lane", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (22, 60, "5", "Dragon book is hot stuff!!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (59, 61, "5", "Hatchet--Fight for the Fittest", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (73, 61, "5", "Hard to put down!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (112, 62, "5", "The Action Keeps Coming", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (69, 62, "5", "Should be read by every American", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (50, 62, "3", "Not a bad checklist...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (112, 62, "5", "The answer to Writers Block!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (53, 63, "4", "Brilliant, except for the bit where Corelli fails to return", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (103, 63, "5", "Read!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (104, 63, "5", "Frightning and compelling", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (86, 64, "4", "An excellent book on what is love.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (86, 64, "4", "a great book for Historical romance lovers", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (97, 64, "5", "Ruth Neary is awesome!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (108, 64, "5", "Its tough everywhere", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (91, 64, "5", "Unpretentious Girl Hero", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (78, 64, "1", "incomplete edition", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (116, 64, "5", "What an Ending", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (119, 64, "4", "Picking Up the Pieces", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (11, 65, "2", "Great book, terrible ending", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (11, 65, "5", "The beginning of something GREAT!!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (106, 65, "1", "Pseudo-intellectual drivel for the true believer", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (74, 65, "5", "A beautifully painful, real story: UPDATE", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (95, 65, "1", "?", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (105, 65, "5", "Tactics of the Cresent Moon Outstanding resourse for Law Enformcement and Homeland Security Practitioners", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (64, 66, "4", "A kind of mellow thriller", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (11, 66, "5", "A unique and inspirational book!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (87, 66, "5", "Freedom is the freedom to say that 2+2=4", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (23, 66, "4", "War is Peace?", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (28, 66, "2", "keep those in-laws happy!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (71, 67, "4", "a good point-but a LONG speech", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (43, 68, "3", "Not as bad as I thought it would be, but....", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (36, 68, "5", "Every Genre has its Masterpiece and this is it...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (39, 68, "5", "Got this for my husband", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (72, 68, "5", "Confusing for a minute then fresh, clear, and exciting", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (29, 68, "1", "The Mother Of His Child-disappointing, unrealistic", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (63, 68, "2", "New genre? Erotica / Spy suspense", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (72, 68, "5", "Great Book", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (25, 68, "4", "Toms Adventures", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (97, 69, "4", "Good one volume review of the law.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (53, 69, "5", "Great for reading to preschool classes", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (9, 69, "5", "Why is this so hard to find?", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (8, 69, "2", "Vampires turn into flying super heroes", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (56, 69, "3", "Over-rated", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (29, 69, "3", "a picaresque jack tale...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (7, 69, "1", "Review of confident student", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (27, 70, "5", "The Adventures of Sherlock Holmes (Illustrated)", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (78, 70, "5", "A must for horror/vampire fans", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (78, 70, "3", "A grand story with promise, but doesnt deliver the goods.", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (7, 70, "5", "Top Notch", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (72, 70, "5", "A Crucial Study", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (16, 70, "5", "Rules for Writers", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (117, 70, "2", "Tis No Angelas Ashes", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (11, 71, "5", "My favourite book in our world!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (8, 71, "5", "A book of exceptional beauty", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (39, 71, "5", "Perspectives", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (111, 71, "5", "Must have!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (7, 71, "3", "Teresa of Avila, breaths, spirits, inspirations & Templars", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (95, 71, "4", "Its alright", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (97, 71, "5", "Informative, fascinating information on Norwegian Kings", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (70, 71, "5", "Well...not everything, but still as good as it gets", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (39, 71, "5", "Incredible Book!!!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (111, 73, "5", "A Life Changing Book...", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (107, 73, "5", "Learning to Learn", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (71, 73, "5", "Playground for your imagination", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (18, 73, "2", "Dont waste your money on this exact reprint of the hardback", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (116, 73, "5", "Classic memoir of the pre and post war Mississippi River", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (7, 73, "5", "The Visual Dictionary of Architecture", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (99, 73, "5", "Nice set", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (10, 73, "4", "Ignore the other reviews! This is another good read from Khushwant Singh", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (29, 73, "2", "If You Like Luke and Laura", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (53, 74, "5", "Excellent depiction of our fearless leader", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (11, 74, "5", "Angels by Billy Graham", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (74, 74, "5", "everythings good!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (72, 74, "2", "Manual - ok quick referance but incomplete details", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (101, 74, "5", "Great antique", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (53, 74, "4", "New insight", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (102, 74, "5", "Suck the marrow from this book!", 1);
INSERT INTO book_rating (book_id, app_user_id, rating, comments, is_published) VALUES (78, 74, "4", "A fun romp!", 1);
