INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (71, 7, 2440, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2440;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (117, 7, 2418, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2418;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (24, 7, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (103, 7, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 7, 233, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 233;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (92, 7, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (71, 8, 2423, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2423;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 8, 1091, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1091;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 8, 1410, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1410;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 8, 391, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 391;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (2, 9, 182, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 182;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 9, 963, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 963;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (118, 9, 1320, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1320;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (99, 9, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (32, 9, 126, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 126;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (10, 10, 1465, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1465;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 10, 1765, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1765;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (92, 10, 880, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 880;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 10, 1017, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1017;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (102, 11, 558, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 558;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (64, 11, 1602, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1602;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (56, 11, 1275, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1275;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 12, 1020, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1020;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 12, 964, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 964;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (1, 12, 2163, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2163;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 13, 977, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 977;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (116, 13, 64, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 64;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (107, 13, 2252, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2252;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (7, 13, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (86, 14, 689, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 689;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (23, 14, 1207, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1207;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 14, 2063, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2063;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 15, 2129, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2129;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (56, 15, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (63, 15, 1980, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1980;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (91, 15, 867, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 867;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (65, 15, 1654, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1654;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (77, 16, 1858, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1858;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 16, 2054, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2054;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (94, 16, 95, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 95;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (120, 17, 2422, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2422;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 17, 214, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 214;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (67, 18, 383, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 383;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (69, 18, 164, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 164;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 18, 695, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 695;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (74, 19, 2249, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2249;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (95, 19, 1508, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1508;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (38, 19, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (82, 19, 662, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 662;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (39, 19, 2477, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2477;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (94, 20, 97, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 97;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (112, 20, 1740, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1740;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (91, 20, 868, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 868;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 20, 407, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 407;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (69, 21, 168, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 168;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 21, 2138, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2138;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 21, 2055, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2055;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (84, 21, 654, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 654;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (120, 22, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (108, 22, 1417, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1417;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (10, 22, 1471, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1471;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (30, 22, 301, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 301;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (71, 22, 2438, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2438;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (63, 23, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 23, 1927, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1927;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (29, 23, 499, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 499;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 23, 965, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 965;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (24, 23, 2453, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2453;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 24, 537, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 537;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (61, 24, 1961, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1961;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (91, 24, 863, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 863;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (116, 24, 52, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 52;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (31, 25, 1890, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1890;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 25, 1401, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1401;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (63, 25, "on hold", 2, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (108, 25, 1443, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1443;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (39, 25, 2487, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2487;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 26, 215, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 215;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (71, 26, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (23, 26, 1227, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1227;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (42, 26, 2401, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2401;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (43, 26, 2090, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2090;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (14, 27, 948, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 948;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (30, 27, 285, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 285;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (12, 28, 922, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 922;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (49, 28, 2344, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2344;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 28, 234, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 234;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (94, 28, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (101, 29, 1, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 29, 392, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 392;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (114, 29, 586, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 586;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 29, 1132, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1132;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (45, 30, 2029, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2029;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (36, 30, 1966, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1966;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 30, 696, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 696;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (89, 30, 1287, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1287;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (52, 31, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (42, 31, 2402, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2402;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (59, 31, 2185, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2185;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 31, 1774, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1774;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 31, 1917, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1917;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (80, 32, 2295, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2295;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (111, 32, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (48, 32, 1536, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1536;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (94, 32, "on hold", 2, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 33, 523, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 523;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 33, 1394, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1394;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 33, 220, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 220;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (62, 33, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (52, 34, 854, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 854;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 34, 393, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 393;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (80, 34, 2287, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2287;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (10, 34, 1467, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1467;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (16, 35, 1697, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1697;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (82, 35, 675, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 675;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 35, 1745, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1745;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (74, 35, 2212, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2212;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (80, 36, 2281, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2281;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (102, 36, 559, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 559;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (101, 36, 18, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 18;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (28, 36, 520, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 520;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 37, 1156, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1156;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (51, 37, 810, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 810;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (92, 37, "on hold", 2, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (56, 37, 1234, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1234;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (27, 37, 2328, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2328;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (116, 38, 33, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 33;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (90, 38, 1647, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1647;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (17, 38, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (8, 38, 780, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 780;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 38, 524, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 524;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (114, 39, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (102, 39, 567, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 567;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (33, 39, 997, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 997;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (66, 39, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 39, 465, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 465;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 39, 2064, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2064;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 40, 2075, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2075;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (80, 40, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (52, 40, 841, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 841;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (89, 40, 1288, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1288;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (27, 40, 2326, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2326;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (69, 41, 153, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 153;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 41, 743, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 743;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (94, 41, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (81, 41, 248, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 248;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (113, 41, 1388, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1388;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 42, 525, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 525;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (14, 42, 949, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 949;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (69, 42, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (43, 42, 2092, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2092;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (36, 42, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (103, 42, 605, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 605;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (45, 43, 2016, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2016;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 43, 2056, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2056;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 43, 1752, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1752;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (60, 44, 2363, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2363;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (8, 44, 794, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 794;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (10, 44, 1468, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1468;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (61, 44, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 45, 697, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 697;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (105, 45, 1193, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1193;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (25, 45, 1821, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1821;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 45, 1402, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1402;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (49, 46, 2348, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2348;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (6, 46, 2149, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2149;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (106, 46, 1591, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1591;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (59, 47, 2203, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2203;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (119, 47, 1710, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1710;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (30, 48, 286, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 286;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (51, 48, 815, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 815;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (94, 48, 98, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 98;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 48, 1395, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1395;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (82, 49, 663, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 663;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (52, 49, 855, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 855;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 49, 1789, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1789;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 49, 724, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 724;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (31, 50, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 50, 1794, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1794;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (100, 50, 1954, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1954;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 50, 1098, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1098;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (99, 50, "on hold", 2, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 51, 957, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 957;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 51, 1399, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1399;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (106, 51, 1592, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1592;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 51, 2117, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2117;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (25, 52, 1847, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1847;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (16, 52, 1684, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1684;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (60, 52, 2365, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2365;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (59, 52, 2204, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2204;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (36, 53, "on hold", 2, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 53, 2130, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2130;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (4, 53, 2457, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2457;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (10, 53, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (68, 53, 373, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 373;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (102, 53, 572, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 572;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (46, 54, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 54, 200, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 200;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (82, 54, 664, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 664;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (56, 54, 1249, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1249;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (89, 54, 1297, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1297;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (69, 55, 165, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 165;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (23, 55, 1214, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1214;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (93, 56, 89, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 89;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (103, 56, 588, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 588;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (18, 57, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 57, 1121, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1121;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 57, 734, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 734;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (77, 58, 1859, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1859;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (33, 58, 992, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 992;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 59, 2065, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2065;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 59, 1411, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1411;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 60, 1021, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1021;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 60, 2076, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2076;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (80, 61, 2282, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2282;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (16, 61, 1679, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1679;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 62, 708, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 708;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (42, 62, 2410, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2410;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (86, 63, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (72, 63, 1055, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1055;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (96, 63, 622, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 622;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (108, 64, 1424, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1424;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (95, 64, 1509, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1509;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 65, 1146, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1146;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 65, 1928, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1928;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (38, 66, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 66, 447, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 447;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 66, 1040, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1040;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 67, 978, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 978;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (45, 67, 2017, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2017;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 68, 221, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 221;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 68, 408, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 408;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (41, 69, 755, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 755;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (77, 69, 1874, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1874;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (103, 70, "on hold", 2, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 70, 1157, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1157;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (2, 70, 169, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 169;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (1, 71, 2164, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2164;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (67, 71, 384, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 384;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 72, 1766, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1766;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (107, 72, 2261, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2261;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 73, 2066, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2066;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (102, 73, 568, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 568;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (64, 74, 1603, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1603;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (81, 74, 249, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 249;