INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (71, 7, 2440, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2440;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (117, 7, 2418, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2418;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (24, 7, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (103, 7, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 7, 233, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 233;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (92, 7, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (71, 8, 2423, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2423;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 8, 1091, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1091;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 8, 1410, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1410;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 8, 391, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 391;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (2, 9, 182, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 182;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 9, 963, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 963;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (118, 9, 1320, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1320;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (99, 9, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (32, 9, 126, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 126;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (10, 10, 1465, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1465;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 10, 1765, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1765;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (92, 10, 880, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 880;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 10, 1017, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1017;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (102, 11, 558, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 558;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (64, 11, 1602, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1602;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (56, 11, 1275, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1275;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 12, 1020, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1020;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 12, 964, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 964;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (1, 12, 2163, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2163;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 13, 977, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 977;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (116, 13, 64, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 64;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (107, 13, 2252, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2252;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (7, 13, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (86, 14, 689, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 689;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (23, 14, 1207, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1207;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 14, 2063, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2063;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 15, 2129, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2129;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (56, 15, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (63, 15, 1980, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1980;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (91, 15, 867, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 867;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (65, 15, 1654, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1654;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (77, 16, 1858, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1858;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 16, 2054, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2054;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (94, 16, 95, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 95;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (120, 17, 2422, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2422;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 17, 214, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 214;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (67, 18, 383, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 383;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (69, 18, 164, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 164;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 18, 695, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 695;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (74, 19, 2249, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2249;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (95, 19, 1508, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1508;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (38, 19, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (82, 19, 662, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 662;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (39, 19, 2477, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2477;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (94, 20, 97, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 97;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (112, 20, 1740, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1740;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (91, 20, 868, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 868;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 20, 407, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 407;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (69, 21, 168, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 168;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 21, 2138, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2138;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 21, 2055, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2055;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (84, 21, 654, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 654;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (120, 22, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (108, 22, 1417, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1417;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (10, 22, 1471, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1471;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (30, 22, 301, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 301;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (71, 22, 2438, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2438;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (63, 23, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 23, 1927, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1927;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (29, 23, 499, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 499;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 23, 965, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 965;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (24, 23, 2453, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2453;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 24, 537, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 537;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (61, 24, 1961, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1961;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (91, 24, 863, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 863;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (116, 24, 52, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 52;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (31, 25, 1890, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1890;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 25, 1401, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1401;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (63, 25, "on hold", 2, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (108, 25, 1443, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1443;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (39, 25, 2487, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2487;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 26, 215, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 215;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (71, 26, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (23, 26, 1227, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1227;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (42, 26, 2401, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2401;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (43, 26, 2090, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2090;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (14, 27, 948, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 948;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (30, 27, 285, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 285;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (12, 28, 922, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 922;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (49, 28, 2344, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2344;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 28, 234, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 234;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (94, 28, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (101, 29, 1, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 29, 392, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 392;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (114, 29, 586, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 586;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 29, 1132, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1132;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (45, 30, 2029, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2029;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (36, 30, 1966, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1966;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 30, 696, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 696;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (89, 30, 1287, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1287;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (52, 31, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (42, 31, 2402, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2402;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (59, 31, 2185, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2185;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 31, 1774, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1774;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 31, 1917, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1917;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (80, 32, 2295, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2295;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (111, 32, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (48, 32, 1536, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1536;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (94, 32, "on hold", 2, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 33, 523, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 523;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 33, 1394, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1394;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 33, 220, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 220;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (62, 33, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (52, 34, 854, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 854;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 34, 393, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 393;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (80, 34, 2287, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2287;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (10, 34, 1467, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1467;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (16, 35, 1697, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1697;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (82, 35, 675, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 675;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 35, 1745, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1745;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (74, 35, 2212, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2212;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (80, 36, 2281, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2281;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (102, 36, 559, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 559;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (101, 36, 18, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 18;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (28, 36, 520, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 520;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 37, 1156, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1156;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (51, 37, 810, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 810;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (92, 37, "on hold", 2, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (56, 37, 1234, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1234;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (27, 37, 2328, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2328;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (116, 38, 33, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 33;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (90, 38, 1647, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1647;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (17, 38, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (8, 38, 780, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 780;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 38, 524, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 524;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (114, 39, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (102, 39, 567, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 567;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (33, 39, 997, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 997;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (66, 39, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 39, 465, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 465;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 39, 2064, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2064;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 40, 2075, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2075;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (80, 40, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (52, 40, 841, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 841;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (89, 40, 1288, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1288;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (27, 40, 2326, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2326;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (69, 41, 153, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 153;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 41, 743, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 743;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (94, 41, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (81, 41, 248, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 248;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (113, 41, 1388, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1388;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 42, 525, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 525;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (14, 42, 949, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 949;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (69, 42, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (43, 42, 2092, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2092;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (36, 42, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (103, 42, 605, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 605;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (45, 43, 2016, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2016;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 43, 2056, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2056;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 43, 1752, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1752;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (60, 44, 2363, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2363;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (8, 44, 794, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 794;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (10, 44, 1468, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1468;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (61, 44, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 45, 697, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 697;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (105, 45, 1193, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1193;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (25, 45, 1821, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1821;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 45, 1402, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1402;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (49, 46, 2348, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2348;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (6, 46, 2149, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2149;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (106, 46, 1591, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1591;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (59, 47, 2203, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2203;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (119, 47, 1710, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1710;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (30, 48, 286, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 286;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (51, 48, 815, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 815;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (94, 48, 98, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 98;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 48, 1395, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1395;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (82, 49, 663, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 663;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (52, 49, 855, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 855;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 49, 1789, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1789;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 49, 724, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 724;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (31, 50, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 50, 1794, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1794;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (100, 50, 1954, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1954;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 50, 1098, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1098;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (99, 50, "on hold", 2, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 51, 957, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 957;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 51, 1399, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1399;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (106, 51, 1592, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1592;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 51, 2117, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2117;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (25, 52, 1847, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1847;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (16, 52, 1684, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1684;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (60, 52, 2365, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2365;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (59, 52, 2204, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2204;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (36, 53, "on hold", 2, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 53, 2130, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2130;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (4, 53, 2457, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2457;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (10, 53, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (68, 53, 373, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 373;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (102, 53, 572, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 572;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (46, 54, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 54, 200, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 200;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (82, 54, 664, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 664;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (56, 54, 1249, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1249;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (89, 54, 1297, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1297;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (69, 55, 165, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 165;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (23, 55, 1214, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1214;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (93, 56, 89, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 89;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (103, 56, 588, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 588;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (18, 57, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 57, 1121, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1121;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 57, 734, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 734;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (77, 58, 1859, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1859;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (33, 58, 992, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 992;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 59, 2065, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2065;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 59, 1411, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1411;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 60, 1021, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1021;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 60, 2076, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2076;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (80, 61, 2282, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2282;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (16, 61, 1679, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1679;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 62, 708, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 708;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (42, 62, 2410, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2410;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (86, 63, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (72, 63, 1055, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1055;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (96, 63, 622, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 622;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (108, 64, 1424, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1424;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (95, 64, 1509, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1509;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 65, 1146, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1146;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 65, 1928, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1928;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (38, 66, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 66, 447, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 447;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 66, 1040, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1040;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 67, 978, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 978;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (45, 67, 2017, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2017;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 68, 221, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 221;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 68, 408, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 408;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (41, 69, 755, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 755;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (77, 69, 1874, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1874;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (103, 70, "on hold", 2, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 70, 1157, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1157;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (2, 70, 169, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 169;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (1, 71, 2164, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2164;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (67, 71, 384, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 384;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 72, 1766, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1766;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (107, 72, 2261, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2261;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 73, 2066, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2066;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (102, 73, 568, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 568;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (64, 74, 1603, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1603;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (81, 74, 249, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 249;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (117, 7, 2415, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2415;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (112, 7, 1728, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1728;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (2, 8, 189, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 189;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 8, 1755, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1755;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (44, 8, 2062, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2062;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (33, 8, 996, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 996;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (69, 9, 162, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 162;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (63, 9, 1992, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1992;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (13, 9, 928, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 928;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (89, 9, 1286, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1286;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (51, 10, 814, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 814;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 10, 969, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 969;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (78, 10, 219, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 219;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (73, 11, 1000, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1000;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (89, 11, 1284, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1284;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 11, 446, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 446;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (103, 11, 587, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 587;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (31, 12, 1888, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1888;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (86, 12, 692, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 692;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 12, 1927, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1927;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (98, 12, 1930, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1930;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (17, 13, 1555, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1555;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 13, 1155, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1155;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 13, 977, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 977;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (69, 13, 168, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 168;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (61, 14, 1959, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1959;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (82, 14, 662, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 662;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (17, 14, 1550, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1550;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (36, 14, 1968, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1968;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (86, 15, 687, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 687;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 15, 406, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 406;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (8, 15, 779, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 779;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (112, 15, 1739, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1739;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (41, 16, 763, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 763;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (103, 16, 620, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 620;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 16, 1913, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1913;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (57, 16, 431, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 431;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (85, 17, 325, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 325;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (30, 17, 299, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 299;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 17, 1127, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1127;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (72, 17, 1046, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1046;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (100, 18, 1954, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1954;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 18, 1793, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1793;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 18, 1928, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1928;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (59, 18, 2199, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2199;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 19, 2115, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2115;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (74, 19, 2246, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2246;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (10, 19, 1466, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1466;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (51, 20, 815, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 815;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (108, 20, 1426, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1426;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 20, 1017, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1017;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (80, 21, 2294, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2294;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (84, 21, 652, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 652;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 21, 1806, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1806;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (59, 21, 2201, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2201;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (108, 22, 1416, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1416;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 22, 419, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 419;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (10, 22, 1470, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1470;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (80, 22, 2281, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2281;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (86, 23, 693, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 693;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (39, 23, 2486, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2486;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (32, 23, 125, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 125;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (63, 23, "on hold", 1, 1);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (13, 23, 929, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 929;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (56, 24, 1246, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1246;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 24, 722, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 722;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (119, 24, 1698, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1698;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (99, 24, 2340, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2340;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 25, 1929, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1929;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (103, 25, 597, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 597;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 25, 2120, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2120;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (85, 25, 334, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 334;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 26, 1767, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1767;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (112, 26, 1725, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1725;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (25, 26, 1827, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1827;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (113, 26, 1387, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1387;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (17, 27, 1549, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1549;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (107, 27, 2259, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2259;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 27, 450, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 450;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 27, 1135, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1135;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (59, 28, 2202, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2202;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (72, 28, 1067, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1067;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (84, 28, 653, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 653;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (24, 28, 2450, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2450;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 29, 1756, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1756;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (41, 29, 755, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 755;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (90, 29, 1638, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1638;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 29, 534, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 534;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 30, 1145, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1145;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (118, 30, 1319, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1319;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (86, 30, 694, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 694;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (36, 31, 1974, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1974;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (85, 31, 326, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 326;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (2, 31, 176, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 176;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (88, 31, 142, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 142;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 32, 2135, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2135;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (71, 32, 2439, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2439;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 32, 1752, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1752;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 32, 1914, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1914;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 33, 451, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 451;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (112, 33, 1740, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1740;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 33, 1119, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1119;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (14, 33, 947, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 947;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 34, 464, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 464;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (91, 34, 861, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 861;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (56, 34, 1247, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1247;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (82, 35, 673, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 673;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (30, 35, 308, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 308;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (77, 35, 1886, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1886;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (45, 35, 2026, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2026;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (120, 36, 2420, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2420;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 36, 1773, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1773;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (34, 36, 742, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 742;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (36, 36, 1975, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1975;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (65, 37, 1668, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1668;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 37, 1807, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1807;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (49, 37, 2344, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2344;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (51, 37, 805, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 805;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 38, 452, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 452;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 38, 1136, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1136;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (36, 38, 1962, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1962;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (45, 38, 2039, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2039;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (8, 39, 790, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 790;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (56, 39, 1248, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1248;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (60, 40, 2358, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2358;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (103, 40, 598, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 598;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (56, 40, 1260, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1260;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (24, 40, 2452, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2452;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (23, 41, 1226, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1226;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (66, 41, 420, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 420;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 41, 1128, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1128;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (42, 42, 2397, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2397;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 42, 453, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 453;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (47, 43, 2102, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2102;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (119, 43, 1707, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1707;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (29, 43, 473, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 473;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (101, 44, 1, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (38, 44, 958, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 958;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (108, 44, 1423, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1423;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (77, 45, 1887, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1887;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (94, 45, 106, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 106;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 45, 1742, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1742;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (52, 45, 838, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 838;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (101, 46, 15, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 15;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (116, 46, 39, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 39;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (71, 47, 2440, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2440;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (59, 47, 2203, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2203;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (53, 47, 1808, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1808;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (119, 47, 1708, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1708;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (50, 48, 454, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 454;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (96, 48, 621, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 621;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (98, 48, 1931, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1931;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (51, 48, 816, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 816;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (92, 49, 910, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 910;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (91, 49, 862, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 862;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (106, 49, 1563, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1563;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 49, 1088, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1088;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (109, 50, 1364, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1364;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (42, 50, 2383, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2383;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (70, 50, 358, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 358;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (92, 50, 903, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 903;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (42, 51, 2400, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2400;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (27, 51, 2320, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2320;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 51, 1137, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1137;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (25, 51, 1828, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1828;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (94, 52, 92, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 92;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (71, 52, 2441, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2441;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 52, 1033, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1033;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 53, 1393, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1393;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (8, 53, 780, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 780;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (91, 53, 867, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 867;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (74, 54, 2247, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2247;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (106, 54, 1564, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1564;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 54, 535, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 535;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (46, 54, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (106, 55, 1575, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1575;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 55, 1743, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1743;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (97, 56, 1039, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1039;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 56, 1915, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1915;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 57, 1120, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1120;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (62, 57, 423, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 423;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (22, 58, 1108, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1108;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (2, 58, 169, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 169;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (116, 59, 50, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 50;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (115, 59, 636, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 636;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (74, 60, 2210, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2210;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (87, 60, 1744, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1744;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (63, 61, 2005, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2005;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (101, 61, 16, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 16;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (72, 62, 1068, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1068;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (16, 62, 1682, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1682;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (73, 63, 999, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 999;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (42, 63, 2398, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2398;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 64, 536, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 536;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 64, 1891, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1891;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (60, 65, 2359, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2359;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (106, 65, 1576, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1576;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (4, 66, 2466, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2466;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (28, 66, 519, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 519;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (57, 67, 432, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 432;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (12, 67, 918, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 918;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (116, 68, 30, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 30;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (92, 68, 879, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 879;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (90, 69, 1639, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1639;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (13, 69, 939, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 939;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (92, 70, 886, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 886;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (111, 70, 1415, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1415;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (113, 71, 1379, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1379;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (46, 71, 2121, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2121;
INSERT INTO book_rental (book_id, app_user_id, rental_status, priority, is_active) VALUES (97, 72, "on hold", 1, 0);
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (72, 72, 1055, "rented", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1055;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (7, 72, 1906, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1906;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (9, 73, 537, "reservation", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 537;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (13, 73, 940, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 940;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (18, 74, 1138, "reservation", 1);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 1138;
INSERT INTO book_rental (book_id, app_user_id, book_copy_id, rental_status, is_active) VALUES (63, 74, 2006, "rented", 0);
UPDATE book_copies_per_school SET availability = 0 WHERE id = 2006;
